# Generated by Django 6.0.4 on 2026-06-23 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'profile__role': 'student'}, related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
